// app/layout.js

import { Inter } from "next/font/google";
import Head from 'next/head'; // Import Head from next/head
import "./globals.css";
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Diversifile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <UserProvider>
        <body>{children}</body>
      </UserProvider>
    </html>
  );
}